sudo: false
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
